name: siged
description: SIGED - Sistema Inteligente de Gestão de Energia Doméstica
publish_to: "none"
version: 2.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  open_filex: ^4.7.0
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  fl_chart: ^0.69.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.5.0
  pdf: ^3.10.8
  path_provider: ^2.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/
  uses-material-design: true
